#!/usr/bin/python3 -u
# The -u makes output unbuffered, so it will show up immediately
import sys
import socket
import select
import json
import time
import random


class Bridge:
    def __init__(self, id):
        self.id = id
        self.root = id
        self.rootPort = -1
        self.cost = 0
        self.desBridge = id

class Port:
    def __init__(self, socket):
        self.port = socket
        self.bpdu = None # Source-id, root-id, cost
        self.flag = True
        self.timeout = 0

    def fileno(self):
        return self.port.fileno()

def current_milliseconds():
    return int(round(time.time() * 1000))


# pads the name with null bytes at the end
def pad(name):
    result = '\0' + name
    while len(result) < 108:
        result += '\0'
    return result


def bpdu(bridge, ports):
    for key, value in ports.items():
        broadcast(bridge.id, 'ffff', 'bpdu',
                  {'id': random.randrange(100000), 'root': bridge.root, 'cost': bridge.cost},
                  value.port)


def broadcast(source, destination, type, message, port):
    port.send(json.JSONEncoder().encode({'source': source,
                                         'dest': destination,
                                         'type': type,
                                         'message': message}).encode())


def read_message(port):
    return json.JSONDecoder().decode(port.port.recv(1500).decode())


def handle_bpdu(bridge, msgPort, message, ports):
    msgBridge = message['source']
    msgRoot = message['root']
    msgCost = message['cost'] + 1
    if (msgRoot < bridge.root) or \
            (not ((msgRoot > bridge.root) or (msgCost > bridge.cost)) and \
                     ((msgCost < bridge.cost) or (msgBridge < bridge.desBridge))):
        if bridge.root != msgRoot:
            print('New root: %s/%s' % (bridge.id, msgRoot))
        if bridge.rootPort != msgPort:
            print('Root port: %s/%d' % (bridge.id, msgPort))
        bridge.root = msgRoot
        bridge.rootPort = msgPort
        bridge.cost = msgCost
        bridge.desBridge = msgBridge
        bpdu(bridge, ports)
    for key in ports.keys():
        port = ports[key]
        if (not port.bpdu is None) and (not (key == msgPort)) and port.flag:
            port_bpdu = port.bpdu
            if ['root'] == msgRoot and port_bpdu['cost'] == msgCost - 1 and \
                port_bpdu['source'] != msgBridge:
                p = key
                if port_bpdu['source'] >= msgBridge:
                    port.flag = False
                else:
                    p = msgPort
                    ports[msgPort].flag = False
                    print('Disabled port: %s/%d' % (bridge.id, p))
            elif port_bpdu['id'] == message['id']:
                ports[msgPort].flag = False
                print('Disabled port: %s/%d' % (bridge.id, msgPort))


def handle_data(source, destination, type, message, msgPort, fft, ports):
    msgID = message['id']
    print('Received message %d on port %d from %s to %s' % (msgID, msgPort, source, destination))
    try:
        portInfo = fft[destination]
        if portInfo[0] == msgPort:
            print('Not forwarding message %d' % msgID)
        elif ports[portInfo[0]].flag:
            print('Forwarding message %d to port %d' % (msgID, portInfo[0]))
            broadcast(source, destination, type, message, ports[portInfo[0]].port)
        else:
            print('Broadcasting message %d to all ports' % msgID)
            for port in openPorts:
                if port != msgPort:
                    broadcast(source, destination, type, message, ports[port].port)
    except KeyError:
        print('Broadcasting message %d to all ports' % msgID)
        for key in ports.keys():
            if key != msgPort and ports[key].flag:
                broadcast(source, destination, type, message, ports[key].port)


def update_fft(fft, source, msgPort):
    fft[source] = [msgPort, current_milliseconds()]


def scrub_fft(fft):
    t = current_milliseconds()
    for key in fft.keys():
        if t - fft[key][1] >= 5000:
            del fft[key]


if __name__ == "__main__":
    LAN = sys.argv[2:]
    bridge = Bridge(sys.argv[1])
    ports = {}
    lastBPDU = 0
    fft = {}

    # creates sockets and connects to them
    for x in range(len(LAN)):
        s = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
        s.connect(pad(LAN[x]))
        ports[x] = Port(s)
    
    print("Bridge %s starting up" % bridge.id)

    # Main loop
    while True:
        if current_milliseconds() - lastBPDU >= 500:
            lastBPDU = current_milliseconds()
            bpdu(bridge, ports)
        scrub_fft(fft)

        ready, ignore, ignore2 = select.select(ports.values(), [], [], 0.5)

        # Reads from each fo the ready sockets
        for key in ports.keys():
            port = ports[key]
            if port in ready:
                msg = read_message(port)
                if msg:
                    source = msg['source']
                    destination = msg['dest']
                    type = msg['type']
                    message = msg['message']

                    if type == 'bpdu':
                        message['source'] = source
                        port.bpdu = message
                        handle_bpdu(bridge, key, message, ports)
                    elif type == 'data':
                        if port.flag:
                            update_fft(fft, source, key)
                            handle_data(source, destination,
                                        type, message, key,
                                        fft, ports)
