#!/usr/bin/python3 -u
import sys
import socket
import select
import json
import time
import random

# represents a bridge which has an id, a root bridge, root port, cost to root, and a
# designated bridge
class Bridge:
    def __init__(self, id):
        self.id = id
        self.root = id
        self.rootPort = -1
        self.cost = 0
        self.desBridge = id

# represents a port which has a socket, most recent bpdu, open flag, and timeout
class Port:
    def __init__(self, socket):
        self.port = socket
        self.bpdus = {} # Source-id: command, timeout, message
        self.alive = True
    
    def status(self):
        temp = 0
        for bpdu in self.bpdus.values():
            temp = max(bpdu[0], temp)
        return temp != 1 and self.alive

    # returns this port's socket's fileno
    def fileno(self):
        return self.port.fileno()

# gets the current milliseconds
def current_milliseconds():
    return int(round(time.time() * 1000))

# pads the name with null bytes at the end
def pad(name):
    result = '\0' + name
    while len(result) < 108:
        result += '\0'
    return result

# sends a bpdu to all given ports
def bpdu(bridge, ports):
    for key, value in ports.items():
        broadcast(bridge.id, "ffff", 'bpdu',
                  {'portkey': key, 'designated': bridge.desBridge,
                   'root': bridge.root, 'cost': bridge.cost},
                  value.port)

# sends a json message on the given port
def broadcast(source, destination, type, message, port):
    port.send(json.JSONEncoder().encode({'source': source,
                                         'dest': destination,
                                         'type': type,
                                         'message': message}).encode())

# reads from the given port and decodes the json
def read_message(port):
    return json.JSONDecoder().decode(port.port.recv(1500).decode())

# handles a bpdu
def handle_bpdu(bridge, msgPort, message, ports):
    msgBridge = message['source']
    msgRoot = message['root']
    msgCost = message['cost'] + 1

    print('Port : %s/%d has status %d' % (bridge.id, msgPort, ports[msgPort].status()))
    command = 0

    # handles the case in which bridge info changes based on the new bpdu
    if (msgRoot < bridge.root) or \
       (not ((msgRoot > bridge.root) or (msgCost > bridge.cost)) and \
       ((msgCost < bridge.cost) or (msgBridge < bridge.desBridge))):
        if bridge.root != msgRoot:
            print('New root: %s/%s' % (bridge.id, msgRoot))
        if bridge.rootPort != msgPort:
            print('Root port: %s/%d' % (bridge.id, msgPort))
            if msgPort in ports[msgPort].bpdus:
                ports[msgPort].bpdus[msgPort][0] = 2
            print('port %d reopened due to bpdu' % (msgPort))
        bridge.root = msgRoot
        bridge.rootPort = msgPort
        bridge.cost = msgCost
        bridge.desBridge = msgBridge
        bpdu(bridge, ports)
        return 2
    # decides how to close ports
    msgCost -= 1
    if msgBridge in ports[msgPort].bpdus and ports[msgPort].bpdus[msgBridge][2] == message:
        return ports[msgPort].bpdus[msgBridge][0]
    if bridge.id == msgBridge and ports[message['portkey']].status() != 1:
        ports[msgPort].alive = False
        print('Killed port %s/%d' % (bridge.id, msgPort))
        return -1
    if msgCost == bridge.cost and bridge.id < msgBridge and bridge.root == msgRoot:
        command = 0
        print('Reopened port: %s/%d due to cost' % (bridge.id, msgPort))
    if ((msgCost == bridge.cost and bridge.id > msgBridge and msgRoot == bridge.root) \
        or (bridge.desBridge == msgBridge and msgBridge != bridge.id \
            and msgPort != bridge.rootPort) \
        or (msgCost < bridge.cost and msgBridge != bridge.desBridge)) \
        and msgPort != bridge.rootPort and ports[msgPort].status() != 1:
        if ports[msgPort].status() < 2:
            print('Disabled port: %s/%d' % (bridge.id, msgPort))
            command = 1
    if message['designated'] == bridge.id:
        command = 2
        print('Reopened port: %s/%d due to designated' % (bridge.id, msgPort))
    if msgBridge in ports[msgPort].bpdus and ports[msgPort].bpdus[msgBridge][2] == message:
        command = ports[msgPort].bpdus[msgBridge][0]
    return command

# handles a data message
def handle_data(source, destination, type, message, msgPort, fft, ports):
    msgID = message['id']
    print('Received message %d on port %d from %s to %s' % (msgID, msgPort, source, destination))
    try:  # ensures that the destination is in the fft, otherwise broadcasts everywhere
        portInfo = fft[destination]
        if portInfo[0] == msgPort:  # message is not sent if it would go out on the same port
            print('Not forwarding message %d, source/port = %s/%d' % (msgID, source, msgPort))
        elif ports[portInfo[0]].status() != 1 and ports[portInfo[0]].alive:
        # makes sure the destination port is open
            print('Forwarding message %d to port %d' % (msgID, portInfo[0]))
            broadcast(source, destination, type, message, ports[portInfo[0]].port)
        else:
            print('Broadcasting message %d to all ports' % msgID)
            for key, value in ports.items():
                if key != msgPort and value.status() != 1 and value.alive:
                    broadcast(source, destination, type, message, value.port)
    except KeyError:
        print('Broadcasting message %d to all ports' % msgID)
        for key in ports.keys():
            if key != msgPort and ports[key].status() != 1 and ports[key].alive:
                broadcast(source, destination, type, message, ports[key].port)

# updates the given fft with new source information
def update_fft(fft, source, msgPort):
    fft[source] = [msgPort, current_milliseconds()]

# returns a new fft which only includes the entries from the given fft that have not timed out
def scrub_fft(fft):
    newFFT = {}
    for key, value in fft.items():
        if current_milliseconds() - value[1] < 5000:
            newFFT[key] = value
    return newFFT

# reopens any ports whose most recent bpdus have timed out
def scrub_ports(ports):
    for key, port in ports.items():
        newBPDUS = {}
        for source, bpdu in port.bpdus.items():
            if current_milliseconds() - bpdu[1] <= 750:
                newBPDUS[source] = bpdu
            else:
                print('Reopened %d due to timeout'% (key))
        port.bpdus = newBPDUS

# main
if __name__ == "__main__":
    LAN = sys.argv[2:]
    # our bridge object, holds onto id, root, root port, etc
    bridge = Bridge(sys.argv[1])
    # dictionary with each key being the port number, each value is a port object
    ports = {}
    # timestamp in milliseconds of the last bpdu received
    lastBPDU = 0
    # dictionary with each key being the destination, each value is list of port number, timestamp
    fft = {}

    # creates sockets and connects to them
    for x in range(len(LAN)):
        s = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
        s.connect(pad(LAN[x]))
        ports[x] = Port(s)
    
    print("Bridge %s starting up" % bridge.id)

    # Main loop
    while True:
        # sends out a new bpdu if 500ms have passed since the last one was sent
        if current_milliseconds() - lastBPDU >= 500:
            bpdu(bridge, ports)
            lastBPDU = current_milliseconds()
        # scrubs out old entries from the fft
        fft = scrub_fft(fft)
        scrub_ports(ports)

        ready, ignore, ignore2 = select.select(ports.values(), [], [], 0.25)

        # Reads from each of the ports
        for key, port in ports.items():
            # only reads from a port if it's ready
            if port in ready:
                msg = read_message(port)
                # ensures there were no issues reading the message
                if msg and port.alive:
                    source = msg['source']
                    destination = msg['dest']
                    type = msg['type']
                    message = msg['message']
                    # handles a bpdu message
                    if type == 'bpdu':
                        message['source'] = source
                        # changes the port's most recent bpdu to the new message
                        command = handle_bpdu(bridge, key, message, ports)
                        if command == -1 or not port.alive:
                            port.bpdus = {}
                        else:
                            port.bpdus[key] = [command, current_milliseconds(), message]
                        print('Port : %s/%d has status %d' % (bridge.id, key, port.status()))
                   # handles a data message
                    elif type == 'data':
                        # only acts on the data message if the port it came in on is open
                        if port.status() != 1:
                            # updates the fft with the new source info
                            update_fft(fft, source, key)
                            handle_data(source, destination,
                                        type, message, key,
                                       fft, ports)
